# Generated by Django 2.2.1 on 2019-05-29 18:10

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20190529_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video',
            field=embed_video.fields.EmbedVideoField(default=''),
        ),
    ]
